apiVersion: meta.dev.upbound.io/v2alpha1
kind: Project
metadata:
  name: crossplane-aws-provider-stack
spec:
  dependsOn:
  - apiVersion: pkg.crossplane.io/v1
    kind: Function
    package: xpkg.crossplane.io/crossplane-contrib/function-auto-ready
    version: '>=v0.6.4'
  - apiVersion: pkg.crossplane.io/v1
    kind: Configuration
    package: ghcr.io/hops-ops/aws-pod-identity
    version: '>=v0.10.1'
  - apiVersion: pkg.crossplane.io/v1
    kind: Provider
    package: xpkg.crossplane.io/crossplane-contrib/provider-family-aws
    version: '>=v2.4.0'
  - apiVersion: pkg.crossplane.io/v1
    kind: Provider
    package: xpkg.crossplane.io/crossplane-contrib/provider-kubernetes
    version: '>=v1'
  description: Installs the Crossplane AWS provider family, selected AWS family providers,
    PodIdentity, and AWS ProviderConfig.
  license: Apache-2.0
  maintainer: Patrick Lee Scott <pat@patscott.io>
  readme: |
    # crossplane-aws-provider-stack
    Installs the Crossplane AWS provider family, selected AWS family providers, PodIdentity, and AWS ProviderConfig.
  repository: ghcr.io/hops-ops/crossplane-aws-provider-stack
  source: github.com/hops-ops/crossplane-aws-provider-stack
