apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: crossplaneawsproviders.aws.hops.ops.com.ai
spec:
  compositeTypeRef:
    apiVersion: aws.hops.ops.com.ai/v1alpha1
    kind: CrossplaneAWSProvider
  mode: Pipeline
  pipeline:
  - functionRef:
      name: hops-ops-crossplane-aws-providerrender
    step: render
  - functionRef:
      name: crossplane-contrib-function-auto-ready
    step: crossplane-contrib-function-auto-ready
